project:
  type: website

format:
  html:
    css: styles.css
    theme: flatly

website:
  title: "Altyn Baigaliyeva"
  navbar:
    sticky: true
    right:
    - icon: file-pdf
      href: files/Altyn-CV.pdf
      aria-label: CV
    - icon: linkedin
      href: https://www.linkedin.com/in/altyn-baigaliyeva/
      aria-label: LinkedIn
    - icon: github
      href: https://github.com/altynliv
      aria-label: GitHub
    - text: About
      href: about.qmd
